version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  movies:
    container_name: movies-api
    depends_on:
      - postgres
      - redis
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - api:/data/api
    restart: unless-stopped

volumes:
  postgres:
  redis:
  api:
